config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  root "topics#index"

  resources :topics do
    resources :comments, only: [:create, :destroy]
    resource  :like,     only: [:create, :destroy]          # Topic用
  end

  resources :comments, only: [] do
    resource :like, controller: "comment_likes", only: [:create, :destroy]  # Comment用
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comment_likes, dependent: :destroy
  def liked_by?(user) = user && comment_likes.exists?(user_id: user.id)
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  
  validates :user_id, uniqueness: { scope: :topic_id }
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many   :comments, dependent: :destroy
  has_one_attached :image
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 80 }
  validates :body,  presence: true


  def liked_by?(user)
    user && likes.exists?(user_id: user.id)
  end


  # シンプル検索（DBに依存しない小ワザ）
  scope :search, ->(q) {
    if q.present?
      where("LOWER(title) LIKE ? OR LOWER(body) LIKE ?", "%#{q.downcase}%", "%#{q.downcase}%")
    else
      all
    end
  }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :topics, dependent: :nullify

  has_many :likes, dependent: :destroy
  has_many :liked_topics, through: :likes, source: :topic

  has_many :comments, dependent: :nullify
  has_many :comment_likes, dependent: :destroy

  has_one_attached :avatar

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  # 全コントローラ共通でログイン必須
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(_resource)  = topics_path
  def after_sign_out_path_for(_resource) = topics_path

  def after_sign_in_path_for(_resource)
    topics_path
  end

  def after_sign_out_path_for(_resource_or_scope)
    topics_path
  end

  def after_sign_up_path_for(_resource)
    topics_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,        keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :email, :password, :password_confirmation, :current_password])
  end

end

app/controllers/comment_likes_controller.rb
class CommentLikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment

  def create
    @comment.comment_likes.find_or_create_by!(user: current_user)
    respond_to do |f|
      f.turbo_stream
      f.html { redirect_to @comment.topic }
    end
  end

  def destroy
    @comment.comment_likes.where(user: current_user).destroy_all
    respond_to do |f|
      f.turbo_stream
      f.html { redirect_to @comment.topic }
    end
  end

  private
  def set_comment; @comment = Comment.find(params[:comment_id]); end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.new(comment_params.merge(user: current_user))
    if @comment.save
      redirect_to @topic, notice: "コメントしました。"
    else
      redirect_to @topic, alert: "コメントできませんでした。"
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.find(params[:id])
    if @comment.user == current_user
      @comment.destroy
      redirect_to @topic, notice: "コメントを削除しました。"
    else
      redirect_to @topic, alert: "削除権限がありません。"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic

  def create
    @topic.likes.find_or_create_by!(user: current_user)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @topic }
    end
  end

  def destroy
    @topic.likes.where(user: current_user).destroy_all
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @topic }
    end
  end

  private
  def set_topic
    @topic = Topic.find(params[:topic_id])
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authorize_owner!, only: [:edit, :update, :destroy]

  def index
    # シンプル検索 + 新しい順 + ページネーション
    @pagy, @topics = pagy(
      Topic.search(params[:q]).includes(:user).order(created_at: :desc)
    )
  end

  def show
    @comment = Comment.new
    @comments = @topic.comments.includes(:user).order(created_at: :asc)
  end

  def new
    @topic = current_user.topics.new
  end

  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to @topic, notice: "投稿しました。"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: "更新しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path, notice: "削除しました。"
  end

  private
  def set_topic
    @topic = Topic.find(params[:id])
  end

  def authorize_owner!
    redirect_to @topic, alert: "編集権限がありません。" unless @topic.user == current_user
  end

  def topic_params
    params.require(:topic).permit(:title, :body, :image)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  # アバターだけ更新するとき、パスワード不要
  protected
  def update_resource(resource, params)
    if params[:password].present? || params[:password_confirmation].present?
      super
    else
      resource.update_without_password(params.except(:current_password))
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

    def avatar_image(user, size: 50, **opts)
    if user&.avatar&.attached? && user.avatar.blob&.persisted?
      image_tag user.avatar.variant(resize_to_fill: [size, size]), **opts
    else
      image_tag "default-avatar.png", width: size, height: size, **opts
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_like_button.html.haml
- liked = user_signed_in? && comment.liked_by?(current_user)
.d-flex.align-items-center
  - if user_signed_in?
    - if liked
      = button_to comment_like_path(comment),
                  method: :delete,
                  class: "p-0 border-0 bg-transparent d-flex align-items-center gap-1 text-danger",
                  form: { data: { turbo: false } } do
        %i.bi.bi-heart-fill.text-danger
      %span= comment.comment_likes.count
    - else
      = button_to comment_like_path(comment),
                  method: :post,
                  class: "p-0 border-0 bg-transparent d-flex align-items-center gap-1 text-muted",
                  form: { data: { turbo: false } } do
        %i.bi.bi-heart.text-muted
      %span= comment.comment_likes.count
  - else
    .d-flex.align-items-center.gap-1.text-muted
      %i.bi.bi-heart.text-muted
      %span= topic.likes.count

app/views/comments/create.html.haml
= turbo_stream.replace dom_id(@comment, :like_area) do
  = render "comments/like_button", comment: @comment

app/views/comments/destroy.html.haml
= turbo_stream.replace dom_id(@comment, :like_area) do
  = render "comments/like_button", comment: @comment

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pastel Board
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    %link{ rel: "stylesheet", href: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" }
  %body
    %nav.navbar.navbar-expand-lg{:style => "background:#FFE2C9;"}
      .container.form-narrow
        %a.navbar-brand.fw-bold{:href => "/"} Board app
        %button.navbar-toggler{"aria-controls" => "nav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#nav", "data-bs-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #nav.collapse.navbar-collapse
          %ul.navbar-nav.me-auto.mb-2.mb-lg-0
          .d-flex.align-items-center.justify-content-between.w-100.gap-3.ms-lg-auto
            - if user_signed_in?
              = link_to "New Topic", new_topic_path, class:"btn btn-warning"
              = link_to edit_user_registration_path,
                        class:"text-decoration-none d-flex align-items-center gap-2" do
                - if current_user.avatar.attached? && current_user.avatar.blob&.persisted?
                  = image_tag current_user.avatar.variant(resize_to_fill: [50,50]), class:"rounded-circle me-2"
                - else
                  = image_tag "default-avatar.png", width:50, height:50, class:"rounded-circle me-2"

                %span= current_user.email.split('@').first

            - else
              = link_to "Log in", new_user_session_path, class:"btn btn-outline-dark"
              = link_to "Sign up", new_user_registration_path, class:"btn btn-warning"
    %main.container.app-container.my-4
      - if notice
        .alert.alert-success= notice
      - if alert
        .alert.alert-danger= alert
      = yield

app/views/likes/create.turbo_stream.haml
= turbo_stream.replace dom_id(@topic, :like_area) do
  = render "topics/like_button", topic: @topic

app/views/likes/destroy.turbo_stream.haml
= turbo_stream.replace dom_id(@topic, :like_area) do
  = render "topics/like_button", topic: @topic

app/views/topics/_form.html.haml
= form_with model: @topic, local: true, html: { multipart: true } do |f|
  .card.border-0.shadow-sm
    .card-body
      .mb-3
        %label.form-label Title
        = f.text_field :title, class:"form-control form-narrow", maxlength: 80
      .mb-3
        %label.form-label Body
        = f.text_area :body, class:"form-control form-narrow", rows: 8
      .mb-3
        %label.form-label Image (optional)
        = f.file_field :image, accept:"image/*", class:"form-control form-narrow"
        - if @topic.image.attached?
          .mt-3
            = image_tag @topic.image.variant(resize_to_limit: [800, 800]), |
              class:"img-fluid rounded"                                    |
      .d-flex.gap-2
        = f.submit (@topic.new_record? ? "Create" : "Update"), class:"btn btn-warning"
        = link_to "Back", topics_path, class:"btn btn-outline-dark"

app/views/topics/_like_button.html.haml
- liked = user_signed_in? && topic.liked_by?(current_user)
.d-flex.align-items-center.gap-1
  - if user_signed_in?
    - if liked
      = button_to topic_like_path(topic),
                  method: :delete,
                  class: "p-0 border-0 bg-transparent text-danger",
                  form: { data: { turbo: false } } do
        %i.bi.bi-heart-fill.text-danger
      %span= topic.likes.count
    - else
      = button_to topic_like_path(topic),
                  method: :post,
                  class: "p-0 border-0 bg-transparent text-muted",
                  form: { data: { turbo: false } } do
        %i.bi.bi-heart.text-muted
      %span= topic.likes.count
  - else
    %i.bi.bi-heart.text-muted
    %span= topic.likes.count

app/views/topics/edit.html.haml
%h1 Topics#edit
%p Find me in app/views/topics/edit.html.erb

app/views/topics/index.html.haml
.card.shadow-sm.border-0.mb-4
  .card-body
    = form_with url: topics_path, method: :get, local: true do |f|
      .input-group
        = f.text_field :q, value:@q, class:"form-control", placeholder:"Search by title or body"
        %button.btn.btn-warning{:type => "submit"} Search
.vstack.gap-3
  - @topics.each do |t|
    .card.border-0.shadow-sm
      .card-body
        .d-flex.justify-content-between
          %h5.card-title.mb-0
            = link_to t.title, t, class:"stretched-link text-decoration-none text-dark"
          %small.text-muted= t.created_at.strftime("%Y-%m-%d %H:%M")
        %p.card-text.mt-2.text-muted= truncate(strip_tags(simple_format(t.body)), length: 160)
        %span.badge.text-bg-warning

        %span.badge.text-muted.d-flex.align-items-center.gap-2
          - if t.user.avatar.attached? && t.user.avatar.blob.persisted?
            = image_tag t.user.avatar.variant(resize_to_fill: [45,45]), class:"rounded-circle"
          - else
            = image_tag "default-avatar.png", width:45, height:45, class:"rounded-circle"

          by #{t.user.email}

        - if t.image.attached?
          %span.badge.text-bg-light.border.ms-2 image
.d-flex.justify-content-center.mt-4
  != pagy_bootstrap_nav(@pagy)

app/views/topics/new.html.haml
%h2.mb-3 New Topic
= render "form"

app/views/topics/show.html.haml
.card.border-0.shadow-sm.mb-4
  .card-body
    .d-flex.justify-content-between.align-items-start
      %h3.card-title.mb-0= @topic.title
      .text-muted= @topic.created_at.strftime("%Y-%m-%d %H:%M")
    .text-muted.mb-2.mt-2
      %span.badge.text-muted.d-flex.align-items-center.gap-2
        - if @topic.user.avatar.attached? && @topic.user.avatar.blob.persisted?
          = image_tag @topic.user.avatar.variant(resize_to_fill: [45,45]), class:"rounded-circle"
        - else
          = image_tag "default-avatar.png", width:45, height:45, class:"rounded-circle"
        by #{@topic.user.email}
    .mt-3
      = simple_format @topic.body
    - if @topic.image.attached?
      .mt-3
        = image_tag @topic.image.variant(resize_to_limit: [1200, 1200]), |
          class:"img-fluid rounded"                                      |
    - if user_signed_in? && @topic.user == current_user
      .mt-3.d-flex.gap-2
        = link_to "Edit", edit_topic_path(@topic), class:"btn btn-warning"
        = button_to "Delete", @topic, method: :delete,            |
          class:"btn btn-outline-danger",                         |
          form: { data: { turbo_confirm: "Delete this topic?" } } |
    %div{ id: dom_id(@topic, :like_area) }
      = render "topics/like_button", topic: @topic


%h4.mb-3
  Comments (#{@comments.size})
.vstack.gap-3.mb-4
  - @comments.each do |c|
    .card.border-0.shadow-sm
      .card-body
        .d-flex.justify-content-between
          .text-muted
            %span.badge.text-muted.d-flex.align-items-center.gap-2
              - if c.user.avatar.attached? && c.user.avatar.blob.persisted?
                = image_tag c.user.avatar.variant(resize_to_fill: [45,45]), class:"rounded-circle"
              - else
                = image_tag "default-avatar.png", width:45, height:45, class:"rounded-circle"

              by #{c.user.email}
          .text-muted.small= c.created_at.strftime("%Y-%m-%d %H:%M")
        .mt-2= simple_format c.body
        %div{ id: dom_id(c, :like_area) }
          = render "comments/like_button", comment: c

        - if user_signed_in? && c.user == current_user
          .mt-2
            = button_to "Delete", topic_comment_path(@topic, c),     |
              method: :delete, class:"btn btn-outline-danger btn-sm" |
- if user_signed_in?
  .card.border-0.shadow-sm
    .card-body
      = form_with model: [@topic, @comment], local: true do |f|
        .mb-2
          = f.text_area :body, rows: 4, class:"form-control", |
            placeholder:"Write a comment..."                  |
        = f.submit "Post comment", class:"btn btn-warning"
- else
  .alert.alert-light.border Please log in to comment.